const fs = require('fs');
const path = 'backend/src/services/workflowGenerator.service.ts';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split('\n');

// Line 1462 (0-indexed is 1461)
const lineIndex = 1461;
console.log('Old line:', lines[lineIndex]);

// Correct line
lines[lineIndex] = '        content: `## Generated by RISE AI\n\n**Request:** ${description}\n\n**Generated:** ${new Date().toLocaleString()}`,';

console.log('New line:', lines[lineIndex]);

fs.writeFileSync(path, lines.join('\n'));
console.log('File updated.');
